# Generated by Django 3.2.9 on 2022-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
